<a href="https://colab.research.google.com/github/sifatullahkarwan/Pytorch-Tutorial/blob/main/prt_2_tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_torch = torch.arange(10)# creates a one-dimensional tensor containing a sequence of numbers.
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch.reshape(2,5)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Reshape if we don't know the number of items -1
my_torch2 = torch.arange(10)
my_torch2.reshape(5,-1)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch4 = torch.arange(15)
my_torch4.view(3,-1)
my_torch4[0]=12# change the item in tensor
my_torch4

tensor([12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#        Difference between View and reshape


As the name suggests, torch.view merely creates a view of the original tensor. The new tensor will always share its data with the original tensor. This means that if you change the original tensor, the reshaped tensor will change and vice versa.

torch.reshape doesn't impose any contiguity constraints, but also doesn't guarantee data sharing. The new tensor may be a view of the original tensor, or it may be a new tensor altogether.



In [ ]:
# Sliceing
my_torch7 = torch.arange(10)
my_torch7
# greb the specific items
my_torch[2]

my_torch8 = my_torch7.reshape(5,2)
my_torch8
my_torch8[:,1]# 1 is column number



tensor([1, 3, 5, 7, 9])

In [ ]:
# Return the column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Math Operation Tensor


In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([6,7,9,10])

# Addition
tensor_a + tensor_b

tensor([ 7,  9, 12, 14])

In [28]:
# Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 7,  9, 12, 14])

In [29]:
# subtracion
tensor_b - tensor_a

tensor([5, 5, 6, 6])

In [30]:
# sub function
torch.sub(tensor_b,tensor_a)

tensor([5, 5, 6, 6])

In [32]:
# Multiplication
tensor_a * tensor_b

tensor([ 6, 14, 27, 40])

In [31]:
# mul longhand fucntion
torch.mul(tensor_a,tensor_b)

tensor([ 6, 14, 27, 40])

In [33]:
# Division
tensor_b / tensor_a

tensor([6.0000, 3.5000, 3.0000, 2.5000])

In [34]:
# div function
torch.div(tensor_b,tensor_a)

tensor([6.0000, 3.5000, 3.0000, 2.5000])

In [35]:
# Remainder % modules
tensor_b % tensor_a

tensor([0, 1, 0, 2])

In [36]:
# Remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 1, 0, 2])

In [38]:
# Exponents / power
torch.pow(tensor_a,tensor_b)

tensor([      1,     128,   19683, 1048576])